filegroup(
    name = "all_files",
    srcs = [
      "usr/share/doc/gcc-12-base/copyright",
      "usr/share/doc/gcc-12-base/changelog.Debian.gz",
      "usr/share/doc/gcc-12-base/README.Debian.amd64.gz",
      "usr/share/doc/gcc-12-base/TODO.Debian",
    ],
    data = [
      
    ],
    visibility = ["//visibility:public"],
)


exports_files([
    "usr/share/doc/gcc-12-base/copyright",
      "usr/share/doc/gcc-12-base/changelog.Debian.gz",
      "usr/share/doc/gcc-12-base/README.Debian.amd64.gz",
      "usr/share/doc/gcc-12-base/TODO.Debian",
])


