filegroup(
    name = "all_files",
    srcs = [
      "usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30",
      "usr/share/gcc/python/libstdcxx/__init__.py",
      "usr/lib/x86_64-linux-gnu/libstdc++.so.6",
      "usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30-gdb.py",
      "usr/share/gcc/python/libstdcxx/v6/__init__.py",
      "usr/share/gcc/python/libstdcxx/v6/xmethods.py",
      "usr/share/gcc/python/libstdcxx/v6/printers.py",
    ],
    data = [
      "@libgcc-s1_amd64//:all_files",
      "@gcc-12-base_amd64//:all_files",
      "@libc6_amd64//:all_files",
    ],
    visibility = ["//visibility:public"],
)


exports_files([
    "usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30",
      "usr/share/gcc/python/libstdcxx/__init__.py",
      "usr/lib/x86_64-linux-gnu/libstdc++.so.6",
      "usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30-gdb.py",
      "usr/share/gcc/python/libstdcxx/v6/__init__.py",
      "usr/share/gcc/python/libstdcxx/v6/xmethods.py",
      "usr/share/gcc/python/libstdcxx/v6/printers.py",
])


